spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5433/TicketSales'
    username: 'postgres'
    password: 'Postgres098'
    driver-class-name: 'org.postgresql.Driver'
jpa:
  show-sql: true
  properties:
    hibernate:
      javax.cache:
        missing_cache_strategy: create
        provider: 'org.ehcache.jsr107.EhcacheCachingProvider'
      cache:
        use_second_level_cache: true
        region.factory_class: 'org.hibernate.cache.jcache.internal.JCacheRegionFactory'
        use_query_cache: true